name: Require Any PR Label
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, reopened]

jobs:
  check-labels:
    name: label-check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write   # to comment
      issues: write
    steps:
      - name: Validate labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const hasLabel = (pr.labels || []).length > 0;
            if (!hasLabel) {
              core.setFailed("PR must include at least one label.");
            }

      - name: Comment when invalid
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: "⚠️ This PR has no labels. Please add at least one label (e.g., NEW FEATURE, BUG FIX, DOCS)."
            });